### ISSUE TITLE
[xcode Error - Still Builds] npm install -g npr-one | xcode-select: error: tool 'xcodebuild' requires Xcode | not CommandLineTools

### ISSUE THREAD

**Issue by BenjaminHCCarr** [adafruit/nprone-cli#2]
> tyr:~ benc$ npm install -g npr-one
> /usr/local/bin/npr-one -> /usr/local/lib/node_modules/npr-one/cli
> 
> dtrace-provider@0.6.0 install /usr/local/lib/node_modules/npr-one/node_modules/dtrace-provider
> node scripts/install.js
> 
> 
> i2c-bus@1.1.0 install /usr/local/lib/node_modules/npr-one/node_modules/i2c-bus
> node-gyp rebuild
> 
> xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
> 
> xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
> 
>   SOLINK_MODULE(target) Release/i2c.node
> /usr/local/lib
> └─┬ npr-one@1.6.0 
>   ├─┬ adafruit-mpr121@1.0.0 
>   │ └─┬ i2c-bus@1.1.0 
>   │   ├── bindings@1.2.1 
>   │   └── nan@2.3.5 
>   ├─┬ chalk@1.1.3 
>   │ ├── ansi-styles@2.2.1 
>   │ ├── escape-string-regexp@1.0.5 
>   │ ├── has-ansi@2.0.0 
>   │ ├── strip-ansi@3.0.1 
>   │ └── supports-color@2.0.0 
>   ├── dotenv@1.2.0 
>   ├─┬ gauge@2.6.0 
>   │ ├── aproba@1.0.4 
>   │ ├── console-control-strings@1.1.0 
>   │ ├── has-color@0.1.7 
>   │ ├── has-unicode@2.0.1 
>   │ ├── object-assign@4.1.0 
>   │ ├── signal-exit@3.0.0 
>   │ ├─┬ string-width@1.0.1 
>   │ │ ├─┬ code-point-at@1.0.0 
>   │ │ │ └── number-is-nan@1.0.0 
>   │ │ └── is-fullwidth-code-point@1.0.0 
>   │ └── wide-align@1.1.0 
>   ├─┬ inquirer@0.9.0 
>   │ ├── ansi-regex@2.0.0 
>   │ ├── cli-width@1.1.1 
>   │ ├── figures@1.7.0 
>   │ ├── lodash@3.10.1 
>   │ ├─┬ readline2@0.1.1 
>   │ │ ├── mute-stream@0.0.4 
>   │ │ └─┬ strip-ansi@2.0.1 
>   │ │   └── ansi-regex@1.1.1 
>   │ ├─┬ run-async@0.1.0 
>   │ │ └─┬ once@1.3.3 
>   │ │   └── wrappy@1.0.2 
>   │ ├── rx-lite@2.5.2 
>   │ └── through@2.3.8 
>   ├── keypress@0.2.1 
>   ├─┬ mplayer@2.1.0 
>   │ └── lodash@2.4.2 
>   ├─┬ npmlog@2.0.4 
>   │ ├── ansi@0.3.1 
>   │ ├─┬ are-we-there-yet@1.1.2 
>   │ │ ├── delegates@1.0.0 
>   │ │ └─┬ readable-stream@2.1.4 
>   │ │   ├── buffer-shims@1.0.0 
>   │ │   ├── core-util-is@1.0.2 
>   │ │   ├── isarray@1.0.0 
>   │ │   ├── process-nextick-args@1.0.7 
>   │ │   ├── string_decoder@0.10.31 
>   │ │   └── util-deprecate@1.0.2 
>   │ └─┬ gauge@1.2.7 
>   │   ├─┬ lodash.pad@4.4.0 
>   │   │ ├── lodash._baseslice@4.0.0 
>   │   │ ├── lodash._basetostring@4.12.0 
>   │   │ └── lodash.tostring@4.1.3 
>   │   ├── lodash.padend@4.5.0 
>   │   └── lodash.padstart@4.5.0 
>   ├─┬ npr-api@2.0.1 
>   │ ├─┬ bunyan@1.8.1 
>   │ │ ├── dtrace-provider@0.6.0 
>   │ │ ├── moment@2.14.1 
>   │ │ ├─┬ mv@2.1.1 
>   │ │ │ ├─┬ mkdirp@0.5.1 
>   │ │ │ │ └── minimist@0.0.8 
>   │ │ │ ├── ncp@2.0.0 
>   │ │ │ └─┬ rimraf@2.4.5 
>   │ │ │   └── glob@6.0.4 
>   │ │ └── safe-json-stringify@1.0.3 
>   │ └─┬ swagger-client@2.1.15 
>   │   ├── btoa@1.1.2 
>   │   ├── cookiejar@2.0.6 
>   │   ├─┬ js-yaml@3.6.1 
>   │   │ ├─┬ argparse@1.0.7 
>   │   │ │ └── sprintf-js@1.0.3 
>   │   │ └── esprima@2.7.2 
>   │   ├── lodash-compat@3.10.2 
>   │   ├── q@1.4.1 
>   │   └─┬ superagent@1.8.3 
>   │     ├── component-emitter@1.2.1 
>   │     ├─┬ debug@2.2.0 
>   │     │ └── ms@0.7.1 
>   │     ├── extend@3.0.0 
>   │     ├─┬ form-data@1.0.0-rc3 
>   │     │ ├── async@1.5.2 
>   │     │ ├─┬ combined-stream@1.0.5 
>   │     │ │ └── delayed-stream@1.0.0 
>   │     │ └─┬ mime-types@2.1.11 
>   │     │   └── mime-db@1.23.0 
>   │     ├── formidable@1.0.17 
>   │     ├── methods@1.1.2 
>   │     ├── mime@1.3.4 
>   │     ├── qs@2.3.3 
>   │     ├─┬ readable-stream@1.0.27-1 
>   │     │ └── isarray@0.0.1 
>   │     └── reduce-component@1.0.1 
>   ├─┬ rimraf@2.5.3 
>   │ └─┬ glob@7.0.5 
>   │   ├── fs.realpath@1.0.0 
>   │   ├── inflight@1.0.5 
>   │   ├── inherits@2.0.1 
>   │   ├─┬ minimatch@3.0.2 
>   │   │ └─┬ brace-expansion@1.1.5 
>   │   │   ├── balanced-match@0.4.1 
>   │   │   └── concat-map@0.0.1 
>   │   └── path-is-absolute@1.0.0 
>   ├── string@3.3.1 
>   ├─┬ touch@1.0.0 
>   │ └─┬ nopt@1.0.10 
>   │   └── abbrev@1.0.9 
>   └─┬ wget-improved@1.3.0 
>     └── tunnel@0.0.2 
> 

> tyr:~ benc$ uname -a
> Darwin tyr.local 14.5.0 Darwin Kernel Version 14.5.0: Thu Apr 21 20:40:54 PDT 2016; root:xnu-2782.50.3~1/RELEASE_X86_64 x86_64
> 
> tyr:~ benc$ node -v
> v6.3.0
> 
> tyr:~ benc$ npm -v
> 3.10.3
> 
> tyr:~ benc$ xcode-select -v
> xcode-select version 2339.

Using '/Library/Developer/CommandLineTools' rather than XCode.app, installed using xcode-select --install

**Comment by toddtreece** [comment]
@BenjaminHCCarr did the install fail, or just the optional `i2c-bus` install?

**Comment by BenjaminHCCarr** [comment]
it built fine, I am running it now.

would also be nice to support mpv.io [a long-term mplayer fork]

don't have time to work on it atm

**Comment by toddtreece** [comment]
k. closing this since the optional dependency `i2c-bus` will fail to install on os x. the project is targeted for installing on a raspi, so os x support is limited.

**Comment by BenjaminHCCarr** [comment]
Actually '/usr/local/lib/node_modules/npr-one/node_modules/i2c-bus' built fine.....

> tyr:~ benc$ ls /usr/local/lib/node_modules/npr-one/node_modules/i2c-bus
> History.md     binding.gyp    example        src
> LICENSE        build          i2c-bus.js     test
> README.md      doc            package.json   win-i2c-bus.js

Thanks for making it work on OSX at all!

I am guessing you haven't tracked it, since you are providing for your own products (boards), but do you know what portion of the code called "xcodebuild"? I forked and searched and can't find it or the i2c ref in the code itself. I see the i2c is a dep on your interface board, so that makes sense.

It would be nice to add an escapr if `process.platform = 'darwin'` to whatever is throwing xcodebuild errors to stdrout, which IS a fix I could do, if I could find it, may have to try installing later with debug on to locate and submit patch against that dep.

**Comment by toddtreece** [comment]
@BenjaminHCCarr as far as i know, there isn't a way to target npm installs for specific platforms, which is why it's installed as an optional dependency.

i'm guessing this is your issue:
https://github.com/nodejs/node-gyp/issues/341

**Comment by BenjaminHCCarr** [comment]
@toddtreece
I have a solution!!!!! I'm on `El Captain 10.11.6` and `npm install -g npr-one` was erroring.
Following your note on nodejs/node-gyp#341 I kept going down links until I got a clean build:

This fixed it, and it's straight forward, it might be worth documenting, or if you want me to add a PR I am happy to:
```
npm install -g node-gyp
npm rebuild
```

At that point I got a clean build of `npr-one`

This was the error before installing `node-gyp`:
```
tyr:~ benc$ npr-one 
                                                                               
 ██████████████████████████████████████████████████████████████████████████████
 ██████████████████████████████████████████████████████████████████████████████
 ██████████████████████████████████████████████████████████████████████████████
 ███████▄▄▄▄▄███▄▄████████████████▄▄▄▄▄███▄▄█████████████████▄▄▄▄▄▄████████████
 ███████████▄▄▄▄███▄██████████████████▄▄▄████▄████████████████████▄▄▄▄█████████
 █████████████████████████████████████████▄████████████████████████████████████
 ███████████████████████████████████████████████████████████████▄██████████████
 █████████████████████████████████████████▄████████████████████████████████████
 ████████████████████████████████████▄▄▄▄████▄█████████████████████████████████
 ███████▄▄▄██████▄▄▄█████████████████▄███▄▄▄█████████████████▄▄▄▄██████████████
 ██████████████████████████████████████████████████████████████████████████████
 ██████████████████████████████████████████████████████████████████████████████
 █████████████████████████████████▄▄▄██████████████████████████████████████████
Error: The module '/usr/local/lib/node_modules/npr-one/node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npr-one/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npr-one/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npr-one/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
connecting to npr one...
^C
tyr:~ benc$ 
tyr:~ benc$ npm install -g npr-one
/usr/local/bin/npr-one -> /usr/local/lib/node_modules/npr-one/cli

> dtrace-provider@0.8.0 install /usr/local/lib/node_modules/npr-one/node_modules/dtrace-provider
> node scripts/install.js


> i2c-bus@1.2.0 install /usr/local/lib/node_modules/npr-one/node_modules/i2c-bus
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  SOLINK_MODULE(target) Release/i2c.node
- has-color@0.1.7 node_modules/npr-one/node_modules/has-color
- lodash._baseslice@4.0.0 node_modules/npr-one/node_modules/lodash._baseslice
- lodash._basetostring@4.12.0 node_modules/npr-one/node_modules/lodash._basetostring
- lodash.tostring@4.1.3 node_modules/npr-one/node_modules/lodash.tostring
- reduce-component@1.0.1 node_modules/npr-one/node_modules/reduce-component
- cookiejar@2.0.6 node_modules/npr-one/node_modules/superagent/node_modules/cookiejar
- isarray@0.0.1 node_modules/npr-one/node_modules/superagent/node_modules/isarray
- readable-stream@1.0.27-1 node_modules/npr-one/node_modules/superagent/node_modules/readable-stream
/usr/local/lib
└─┬ npr-one@1.6.1 
  ├─┬ adafruit-mpr121@1.0.0
  │ └─┬ i2c-bus@1.2.0 
  │   └── nan@2.5.0 
  ├─┬ gauge@2.7.2 
  │ ├── object-assign@4.1.1 
  │ ├── signal-exit@3.0.2 
  │ ├─┬ string-width@1.0.2 
  │ │ ├── code-point-at@1.1.0 
  │ │ └─┬ is-fullwidth-code-point@1.0.0
  │ │   └── number-is-nan@1.0.1 
  │ └── supports-color@0.2.0 
  ├─┬ inquirer@0.9.0
  │ ├── ansi-regex@2.1.1 
  │ └─┬ run-async@0.1.0
  │   └── once@1.4.0 
  ├─┬ npmlog@2.0.4
  │ ├─┬ are-we-there-yet@1.1.2
  │ │ └── readable-stream@2.2.2 
  │ └─┬ gauge@1.2.7
  │   ├── lodash.pad@4.5.1 
  │   ├── lodash.padend@4.6.1 
  │   └── lodash.padstart@4.6.1 
  ├─┬ npr-api@2.0.1
  │ ├─┬ bunyan@1.8.5 
  │ │ ├── dtrace-provider@0.8.0 
  │ │ └── moment@2.17.1 
  │ └─┬ swagger-client@2.1.32 
  │   ├─┬ js-yaml@3.7.0 
  │   │ ├── argparse@1.0.9 
  │   │ └── esprima@2.7.3 
  │   └─┬ superagent@2.3.0 
  │     ├─┬ debug@2.6.0 
  │     │ └── ms@0.7.2 
  │     ├─┬ form-data@1.0.0-rc4 
  │     │ └─┬ mime-types@2.1.14 
  │     │   └── mime-db@1.26.0 
  │     ├── formidable@1.1.1 
  │     └── qs@6.3.0 
  ├─┬ rimraf@2.5.4 
  │ └─┬ glob@7.1.1 
  │   ├── inflight@1.0.6 
  │   ├── inherits@2.0.3 
  │   ├─┬ minimatch@3.0.3 
  │   │ └── brace-expansion@1.1.6 
  │   └── path-is-absolute@1.0.1 
  ├── string@3.3.3 
  └─┬ wget-improved@1.4.0 
    └── minimist@1.2.0 
```

So it looks like it is fixed upstream, but has a dep on `node-gyp` in the tree.
